// This file is auto-generated by @hey-api/openapi-ts

export const AnswerInSchema = {
    properties: {
        question_id: {
            type: 'integer',
            title: 'Question Id'
        },
        option_id: {
            type: 'integer',
            title: 'Option Id'
        }
    },
    type: 'object',
    required: ['question_id', 'option_id'],
    title: 'AnswerIn'
} as const;

export const AnswerResultCompletedSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'completed',
            title: 'Status'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        top_weaknesses: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Top Weaknesses'
        }
    },
    type: 'object',
    required: ['status', 'session_id', 'top_weaknesses'],
    title: 'AnswerResultCompleted'
} as const;

export const AnswerResultInProgressSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'in_progress',
            title: 'Status'
        },
        next_question: {
            '$ref': '#/components/schemas/AuditQuestionPublic'
        },
        questions_answered: {
            type: 'integer',
            title: 'Questions Answered'
        },
        questions_total: {
            type: 'integer',
            title: 'Questions Total'
        }
    },
    type: 'object',
    required: ['status', 'next_question', 'questions_answered', 'questions_total'],
    title: 'AnswerResultInProgress'
} as const;

export const AspiceLevelEnumSchema = {
    type: 'string',
    enum: ['L1', 'L2', 'L3'],
    title: 'AspiceLevelEnum'
} as const;

export const AuditOptionPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        option_text: {
            type: 'string',
            title: 'Option Text'
        },
        weight: {
            type: 'integer',
            title: 'Weight'
        }
    },
    type: 'object',
    required: ['id', 'label', 'option_text', 'weight'],
    title: 'AuditOptionPublic'
} as const;

export const AuditQuestionPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        question_code: {
            type: 'string',
            title: 'Question Code'
        },
        base_practice_id: {
            type: 'string',
            title: 'Base Practice Id'
        },
        process: {
            '$ref': '#/components/schemas/ProcessEnum'
        },
        level: {
            '$ref': '#/components/schemas/AspiceLevelEnum'
        },
        stakeholders: {
            items: {
                '$ref': '#/components/schemas/StakeholderRoleEnum'
            },
            type: 'array',
            title: 'Stakeholders'
        },
        question_text: {
            type: 'string',
            title: 'Question Text'
        },
        recommendation_logic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Logic'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/AuditOptionPublic'
            },
            type: 'array',
            title: 'Options',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'question_code', 'base_practice_id', 'process', 'level', 'stakeholders', 'question_text', 'is_active'],
    title: 'AuditQuestionPublic'
} as const;

export const AuditSessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        status: {
            '$ref': '#/components/schemas/SessionStatusEnum'
        },
        questions_asked: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Questions Asked'
        },
        max_questions: {
            type: 'integer',
            title: 'Max Questions'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'status', 'questions_asked', 'max_questions', 'started_at'],
    title: 'AuditSessionPublic'
} as const;

export const BanditAnalyticsSchema = {
    properties: {
        arms: {
            items: {
                '$ref': '#/components/schemas/BanditArmStats'
            },
            type: 'array',
            title: 'Arms'
        }
    },
    type: 'object',
    required: ['arms'],
    title: 'BanditAnalytics'
} as const;

export const BanditArmStatsSchema = {
    properties: {
        question_id: {
            type: 'integer',
            title: 'Question Id'
        },
        question_code: {
            type: 'string',
            title: 'Question Code'
        },
        process: {
            type: 'string',
            title: 'Process'
        },
        level: {
            type: 'string',
            title: 'Level'
        },
        pull_count: {
            type: 'integer',
            title: 'Pull Count'
        },
        avg_reward: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Reward'
        }
    },
    type: 'object',
    required: ['question_id', 'question_code', 'process', 'level', 'pull_count', 'avg_reward'],
    title: 'BanditArmStats'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        owner_id: {
            type: 'integer',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OptionInSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 5,
            title: 'Label'
        },
        option_text: {
            type: 'string',
            maxLength: 1000,
            title: 'Option Text'
        },
        weight: {
            type: 'integer',
            maximum: 4,
            minimum: 0,
            title: 'Weight'
        }
    },
    type: 'object',
    required: ['label', 'option_text', 'weight'],
    title: 'OptionIn'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProcessEnumSchema = {
    type: 'string',
    enum: ['SWE1', 'SWE2', 'SWE3', 'SWE4', 'SWE5', 'SWE6'],
    title: 'ProcessEnum'
} as const;

export const QuestionInSchema = {
    properties: {
        question_code: {
            type: 'string',
            maxLength: 50,
            title: 'Question Code'
        },
        base_practice_id: {
            type: 'string',
            maxLength: 50,
            title: 'Base Practice Id'
        },
        process: {
            '$ref': '#/components/schemas/ProcessEnum'
        },
        level: {
            '$ref': '#/components/schemas/AspiceLevelEnum'
        },
        stakeholders: {
            items: {
                '$ref': '#/components/schemas/StakeholderRoleEnum'
            },
            type: 'array',
            title: 'Stakeholders',
            default: []
        },
        question_text: {
            type: 'string',
            maxLength: 2048,
            title: 'Question Text'
        },
        recommendation_logic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Logic'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/OptionIn'
            },
            type: 'array',
            minItems: 1,
            title: 'Options'
        }
    },
    type: 'object',
    required: ['question_code', 'base_practice_id', 'process', 'level', 'question_text', 'options'],
    title: 'QuestionIn'
} as const;

export const QuestionUpdateSchema = {
    properties: {
        base_practice_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Practice Id'
        },
        process: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProcessEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        level: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AspiceLevelEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        stakeholders: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/StakeholderRoleEnum'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stakeholders'
        },
        question_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Text'
        },
        recommendation_logic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recommendation Logic'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        options: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/OptionIn'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Options'
        }
    },
    type: 'object',
    title: 'QuestionUpdate'
} as const;

export const RoleStatsSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        total_users: {
            type: 'integer',
            title: 'Total Users'
        },
        sessions_started: {
            type: 'integer',
            title: 'Sessions Started'
        },
        sessions_completed: {
            type: 'integer',
            title: 'Sessions Completed'
        }
    },
    type: 'object',
    required: ['role', 'total_users', 'sessions_started', 'sessions_completed'],
    title: 'RoleStats'
} as const;

export const SeedInSchema = {
    properties: {
        questions: {
            items: {
                '$ref': '#/components/schemas/QuestionIn'
            },
            type: 'array',
            title: 'Questions'
        }
    },
    type: 'object',
    required: ['questions'],
    title: 'SeedIn'
} as const;

export const SeedResultSchema = {
    properties: {
        inserted: {
            type: 'integer',
            title: 'Inserted'
        },
        skipped: {
            type: 'integer',
            title: 'Skipped'
        }
    },
    type: 'object',
    required: ['inserted', 'skipped'],
    title: 'SeedResult'
} as const;

export const SessionStartSchema = {
    properties: {
        session: {
            '$ref': '#/components/schemas/AuditSessionPublic'
        },
        first_question: {
            '$ref': '#/components/schemas/AuditQuestionPublic'
        }
    },
    type: 'object',
    required: ['session', 'first_question'],
    title: 'SessionStart',
    description: 'Response for POST /audit/sessions/ — session metadata + first question.'
} as const;

export const SessionStatusEnumSchema = {
    type: 'string',
    enum: ['in_progress', 'completed', 'abandoned'],
    title: 'SessionStatusEnum'
} as const;

export const StakeholderRoleEnumSchema = {
    type: 'string',
    enum: ['software_developer', 'software_architect', 'project_manager', 'qa_engineer', 'test_engineer', 'team_lead', 'aspice_assessor'],
    title: 'StakeholderRoleEnum'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        stakeholder_role: {
            '$ref': '#/components/schemas/StakeholderRoleEnum',
            default: 'software_developer'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        stakeholder_role: {
            '$ref': '#/components/schemas/StakeholderRoleEnum',
            default: 'software_developer'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_login_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        stakeholder_role: {
            '$ref': '#/components/schemas/StakeholderRoleEnum',
            default: 'software_developer'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersAnalyticsSchema = {
    properties: {
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleStats'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['roles'],
    title: 'UsersAnalytics'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WeaknessHeatmapSchema = {
    properties: {
        scores: {
            additionalProperties: {
                additionalProperties: {
                    anyOf: [
                        {
                            type: 'number'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                type: 'object'
            },
            type: 'object',
            title: 'Scores'
        },
        session_count: {
            type: 'integer',
            title: 'Session Count'
        }
    },
    type: 'object',
    required: ['scores', 'session_count'],
    title: 'WeaknessHeatmap',
    description: 'Average weakness scores across all completed sessions, per (process, level).'
} as const;

export const WeaknessResultPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        scores: {
            additionalProperties: true,
            type: 'object',
            title: 'Scores'
        },
        top_weaknesses: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Top Weaknesses'
        },
        computed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Computed At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'scores', 'top_weaknesses', 'computed_at'],
    title: 'WeaknessResultPublic'
} as const;