// This file is auto-generated by @hey-api/openapi-ts

export type AnswerIn = {
    question_id: number;
    option_id: number;
};

export type AnswerResultCompleted = {
    status: "completed";
    session_id: string;
    top_weaknesses: Array<(string)>;
};

export type AnswerResultInProgress = {
    status: "in_progress";
    next_question: AuditQuestionPublic;
    questions_answered: number;
    questions_total: number;
};

export type AspiceLevelEnum = 'L1' | 'L2' | 'L3';

export type AuditOptionPublic = {
    id: number;
    label: string;
    option_text: string;
    weight: number;
};

export type AuditQuestionPublic = {
    id: number;
    question_code: string;
    base_practice_id: string;
    process: ProcessEnum;
    level: AspiceLevelEnum;
    stakeholders: Array<StakeholderRoleEnum>;
    question_text: string;
    recommendation_logic?: (string | null);
    is_active: boolean;
    options?: Array<AuditOptionPublic>;
};

export type AuditSessionPublic = {
    id: string;
    user_id: number;
    status: SessionStatusEnum;
    questions_asked: Array<(number)>;
    max_questions: number;
    started_at: string;
    completed_at?: (string | null);
};

export type BanditAnalytics = {
    arms: Array<BanditArmStats>;
};

export type BanditArmStats = {
    question_id: number;
    question_code: string;
    process: string;
    level: string;
    pull_count: number;
    avg_reward: (number | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: number;
    owner_id: number;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OptionIn = {
    label: string;
    option_text: string;
    weight: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProcessEnum = 'SWE1' | 'SWE2' | 'SWE3' | 'SWE4' | 'SWE5' | 'SWE6';

export type QuestionIn = {
    question_code: string;
    base_practice_id: string;
    process: ProcessEnum;
    level: AspiceLevelEnum;
    stakeholders?: Array<StakeholderRoleEnum>;
    question_text: string;
    recommendation_logic?: (string | null);
    options: Array<OptionIn>;
};

export type QuestionUpdate = {
    base_practice_id?: (string | null);
    process?: (ProcessEnum | null);
    level?: (AspiceLevelEnum | null);
    stakeholders?: (Array<StakeholderRoleEnum> | null);
    question_text?: (string | null);
    recommendation_logic?: (string | null);
    is_active?: (boolean | null);
    options?: (Array<OptionIn> | null);
};

export type RoleStats = {
    role: string;
    total_users: number;
    sessions_started: number;
    sessions_completed: number;
};

export type SeedIn = {
    questions: Array<QuestionIn>;
};

export type SeedResult = {
    inserted: number;
    skipped: number;
};

/**
 * Response for POST /audit/sessions/ — session metadata + first question.
 */
export type SessionStart = {
    session: AuditSessionPublic;
    first_question: AuditQuestionPublic;
};

export type SessionStatusEnum = 'in_progress' | 'completed' | 'abandoned';

export type StakeholderRoleEnum = 'software_developer' | 'software_architect' | 'project_manager' | 'qa_engineer' | 'test_engineer' | 'team_lead' | 'aspice_assessor';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    stakeholder_role?: StakeholderRoleEnum;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    stakeholder_role?: StakeholderRoleEnum;
    id: number;
    created_at?: (string | null);
    last_login_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersAnalytics = {
    roles: Array<RoleStats>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    stakeholder_role?: StakeholderRoleEnum;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Average weakness scores across all completed sessions, per (process, level).
 */
export type WeaknessHeatmap = {
    scores: {
        [key: string]: {
            [key: string]: (number | null);
        };
    };
    session_count: number;
};

export type WeaknessResultPublic = {
    id: string;
    session_id: string;
    scores: {
        [key: string]: unknown;
    };
    top_weaknesses: Array<(string)>;
    computed_at: string;
};

export type AnalyticsAggregateWeaknessesResponse = (WeaknessHeatmap);

export type AnalyticsUserStatsResponse = (UsersAnalytics);

export type AnalyticsBanditPerformanceResponse = (BanditAnalytics);

export type AuditStartSessionResponse = (SessionStart);

export type AuditListSessionsData = {
    limit?: number;
    skip?: number;
};

export type AuditListSessionsResponse = (Array<AuditSessionPublic>);

export type AuditGetSessionData = {
    sessionId: string;
};

export type AuditGetSessionResponse = (AuditSessionPublic);

export type AuditSubmitAnswerData = {
    requestBody: AnswerIn;
    sessionId: string;
};

export type AuditSubmitAnswerResponse = ((AnswerResultInProgress | AnswerResultCompleted));

export type AuditGetResultsData = {
    sessionId: string;
};

export type AuditGetResultsResponse = (WeaknessResultPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuestionsListQuestionsData = {
    isActive?: (boolean | null);
    level?: (AspiceLevelEnum | null);
    limit?: number;
    process?: (ProcessEnum | null);
    skip?: number;
};

export type QuestionsListQuestionsResponse = (Array<AuditQuestionPublic>);

export type QuestionsCreateQuestionData = {
    requestBody: QuestionIn;
};

export type QuestionsCreateQuestionResponse = (AuditQuestionPublic);

export type QuestionsUpdateQuestionData = {
    questionId: number;
    requestBody: QuestionUpdate;
};

export type QuestionsUpdateQuestionResponse = (AuditQuestionPublic);

export type QuestionsDeactivateQuestionData = {
    questionId: number;
};

export type QuestionsDeactivateQuestionResponse = (Message);

export type QuestionsSeedQuestionsData = {
    requestBody: SeedIn;
};

export type QuestionsSeedQuestionsResponse = (SeedResult);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);