// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DifficultyEnum = 'easy' | 'medium' | 'hard';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PopularQuizPublic = {
    id: string;
    title: string;
    attempts: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionCreate = {
    question_text: string;
    options: Array<(string)>;
    correct_answer: string;
    explanation?: (string | null);
    points?: number;
};

export type QuestionPublic = {
    id: string;
    quiz_id: string;
    question_text: string;
    options: Array<(string)>;
    correct_answer: string;
    explanation?: (string | null);
    points: number;
    order: number;
};

export type QuizCreate = {
    title: string;
    description?: (string | null);
    difficulty?: DifficultyEnum;
    category: string;
    time_limit?: (number | null);
    passing_score?: number;
    questions?: Array<QuestionCreate>;
};

export type QuizPublic = {
    title: string;
    description?: (string | null);
    difficulty?: DifficultyEnum;
    category: string;
    time_limit?: (number | null);
    passing_score?: number;
    id: string;
    status: QuizStatusEnum;
    creator_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    question_count?: number;
};

export type QuizStatisticsPublic = {
    total_quizzes: number;
    published_quizzes: number;
    unpublished_quizzes: number;
    quizzes_by_category: {
        [key: string]: (number);
    };
    quizzes_by_difficulty: {
        [key: string]: (number);
    };
    average_attempts_per_quiz: number;
    most_popular_quizzes: Array<PopularQuizPublic>;
};

export type QuizStatusEnum = 'draft' | 'published' | 'unpublished';

export type QuizUpdate = {
    title?: (string | null);
    description?: (string | null);
    difficulty?: (DifficultyEnum | null);
    category?: (string | null);
    time_limit?: (number | null);
    passing_score?: (number | null);
    status?: (QuizStatusEnum | null);
    questions?: (Array<QuestionCreate> | null);
};

export type QuizWithQuestions = {
    title: string;
    description?: (string | null);
    difficulty?: DifficultyEnum;
    category: string;
    time_limit?: (number | null);
    passing_score?: number;
    id: string;
    status: QuizStatusEnum;
    creator_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    question_count?: number;
    questions?: Array<QuestionPublic>;
};

export type QuizzesPublic = {
    data: Array<QuizPublic>;
    count: number;
};

export type RecentAttemptPublic = {
    id: string;
    quiz_id: string;
    quiz_title: string;
    user_id: string;
    user_full_name?: (string | null);
    user_email: string;
    score: number;
    passed: boolean;
    completed_at?: (string | null);
};

export type StatisticsPublic = {
    total_users: number;
    active_users: number;
    total_quizzes: number;
    published_quizzes: number;
    unpublished_quizzes: number;
    total_attempts: number;
    average_score: number;
    recent_attempts?: Array<RecentAttemptPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    last_login_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStatisticsPublic = {
    total_users: number;
    active_users: number;
    new_users_this_month: number;
    admin_users: number;
    regular_users: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuizzesReadQuizzesData = {
    category?: (string | null);
    difficulty?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type QuizzesReadQuizzesResponse = (QuizzesPublic);

export type QuizzesCreateQuizData = {
    requestBody: QuizCreate;
};

export type QuizzesCreateQuizResponse = (QuizWithQuestions);

export type QuizzesUpdateQuizData = {
    id: string;
    requestBody: QuizUpdate;
};

export type QuizzesUpdateQuizResponse = (QuizWithQuestions);

export type QuizzesDeleteQuizData = {
    id: string;
};

export type QuizzesDeleteQuizResponse = (Message);

export type QuizzesTogglePublishQuizData = {
    id: string;
};

export type QuizzesTogglePublishQuizResponse = (QuizPublic);

export type StatisticsGetDashboardSummaryResponse = (StatisticsPublic);

export type StatisticsGetUserStatisticsResponse = (UserStatisticsPublic);

export type StatisticsGetQuizStatisticsResponse = (QuizStatisticsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);