/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminQuizzesRouteImport } from './routes/_layout/admin-quizzes'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutQuizzesIndexRouteImport } from './routes/_layout/quizzes/index'
import { Route as LayoutQuizzesQuizIdIndexRouteImport } from './routes/_layout/quizzes/$quizId/index'
import { Route as LayoutAuditSessionIdIndexRouteImport } from './routes/_layout/audit/$sessionId/index'
import { Route as LayoutAuditSessionIdResultsRouteImport } from './routes/_layout/audit/$sessionId/results'
import { Route as LayoutQuizzesQuizIdResultResultIdRouteImport } from './routes/_layout/quizzes/$quizId/result/$resultId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminQuizzesRoute = LayoutAdminQuizzesRouteImport.update({
  id: '/admin-quizzes',
  path: '/admin-quizzes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizzesIndexRoute = LayoutQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizzesQuizIdIndexRoute =
  LayoutQuizzesQuizIdIndexRouteImport.update({
    id: '/quizzes/$quizId/',
    path: '/quizzes/$quizId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuditSessionIdIndexRoute =
  LayoutAuditSessionIdIndexRouteImport.update({
    id: '/audit/$sessionId/',
    path: '/audit/$sessionId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuditSessionIdResultsRoute =
  LayoutAuditSessionIdResultsRouteImport.update({
    id: '/audit/$sessionId/results',
    path: '/audit/$sessionId/results',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutQuizzesQuizIdResultResultIdRoute =
  LayoutQuizzesQuizIdResultResultIdRouteImport.update({
    id: '/quizzes/$quizId/result/$resultId',
    path: '/quizzes/$quizId/result/$resultId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-quizzes': typeof LayoutAdminQuizzesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/quizzes/': typeof LayoutQuizzesIndexRoute
  '/audit/$sessionId/results': typeof LayoutAuditSessionIdResultsRoute
  '/audit/$sessionId/': typeof LayoutAuditSessionIdIndexRoute
  '/quizzes/$quizId/': typeof LayoutQuizzesQuizIdIndexRoute
  '/quizzes/$quizId/result/$resultId': typeof LayoutQuizzesQuizIdResultResultIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-quizzes': typeof LayoutAdminQuizzesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/quizzes': typeof LayoutQuizzesIndexRoute
  '/audit/$sessionId/results': typeof LayoutAuditSessionIdResultsRoute
  '/audit/$sessionId': typeof LayoutAuditSessionIdIndexRoute
  '/quizzes/$quizId': typeof LayoutQuizzesQuizIdIndexRoute
  '/quizzes/$quizId/result/$resultId': typeof LayoutQuizzesQuizIdResultResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/admin-quizzes': typeof LayoutAdminQuizzesRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/quizzes/': typeof LayoutQuizzesIndexRoute
  '/_layout/audit/$sessionId/results': typeof LayoutAuditSessionIdResultsRoute
  '/_layout/audit/$sessionId/': typeof LayoutAuditSessionIdIndexRoute
  '/_layout/quizzes/$quizId/': typeof LayoutQuizzesQuizIdIndexRoute
  '/_layout/quizzes/$quizId/result/$resultId': typeof LayoutQuizzesQuizIdResultResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-quizzes'
    | '/dashboard'
    | '/history'
    | '/items'
    | '/settings'
    | '/quizzes/'
    | '/audit/$sessionId/results'
    | '/audit/$sessionId/'
    | '/quizzes/$quizId/'
    | '/quizzes/$quizId/result/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-quizzes'
    | '/dashboard'
    | '/history'
    | '/items'
    | '/settings'
    | '/'
    | '/quizzes'
    | '/audit/$sessionId/results'
    | '/audit/$sessionId'
    | '/quizzes/$quizId'
    | '/quizzes/$quizId/result/$resultId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/admin-quizzes'
    | '/_layout/dashboard'
    | '/_layout/history'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/quizzes/'
    | '/_layout/audit/$sessionId/results'
    | '/_layout/audit/$sessionId/'
    | '/_layout/quizzes/$quizId/'
    | '/_layout/quizzes/$quizId/result/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-quizzes': {
      id: '/_layout/admin-quizzes'
      path: '/admin-quizzes'
      fullPath: '/admin-quizzes'
      preLoaderRoute: typeof LayoutAdminQuizzesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quizzes/': {
      id: '/_layout/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof LayoutQuizzesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quizzes/$quizId/': {
      id: '/_layout/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId/'
      preLoaderRoute: typeof LayoutQuizzesQuizIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit/$sessionId/': {
      id: '/_layout/audit/$sessionId/'
      path: '/audit/$sessionId'
      fullPath: '/audit/$sessionId/'
      preLoaderRoute: typeof LayoutAuditSessionIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit/$sessionId/results': {
      id: '/_layout/audit/$sessionId/results'
      path: '/audit/$sessionId/results'
      fullPath: '/audit/$sessionId/results'
      preLoaderRoute: typeof LayoutAuditSessionIdResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quizzes/$quizId/result/$resultId': {
      id: '/_layout/quizzes/$quizId/result/$resultId'
      path: '/quizzes/$quizId/result/$resultId'
      fullPath: '/quizzes/$quizId/result/$resultId'
      preLoaderRoute: typeof LayoutQuizzesQuizIdResultResultIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAdminQuizzesRoute: typeof LayoutAdminQuizzesRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQuizzesIndexRoute: typeof LayoutQuizzesIndexRoute
  LayoutAuditSessionIdResultsRoute: typeof LayoutAuditSessionIdResultsRoute
  LayoutAuditSessionIdIndexRoute: typeof LayoutAuditSessionIdIndexRoute
  LayoutQuizzesQuizIdIndexRoute: typeof LayoutQuizzesQuizIdIndexRoute
  LayoutQuizzesQuizIdResultResultIdRoute: typeof LayoutQuizzesQuizIdResultResultIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAdminQuizzesRoute: LayoutAdminQuizzesRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQuizzesIndexRoute: LayoutQuizzesIndexRoute,
  LayoutAuditSessionIdResultsRoute: LayoutAuditSessionIdResultsRoute,
  LayoutAuditSessionIdIndexRoute: LayoutAuditSessionIdIndexRoute,
  LayoutQuizzesQuizIdIndexRoute: LayoutQuizzesQuizIdIndexRoute,
  LayoutQuizzesQuizIdResultResultIdRoute:
    LayoutQuizzesQuizIdResultResultIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
