import type { Quiz, QuizAttempt } from "@/types/quiz"

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: "swe1-quiz",
    title: "SWE.1 – Software Requirements Analysis",
    description:
      "Assess your understanding of software requirements elicitation, analysis, and management within ASPICE SWE.1 processes.",
    category: "Requirements",
    difficulty: "medium",
    timeLimit: 15,
    passingScore: 70,
    isPublished: true,
    attemptCount: 0,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe1-q1",
        quizId: "swe1-quiz",
        type: "multiple-choice",
        text: "What is the primary purpose of SWE.1 in ASPICE?",
        questionText: "What is the primary purpose of SWE.1 in ASPICE?",
        options: [
          { id: "a", text: "To define the architecture of the software system" },
          { id: "b", text: "To specify software requirements derived from system requirements" },
          { id: "c", text: "To verify software units through testing" },
          { id: "d", text: "To integrate software components" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "SWE.1 focuses on establishing and maintaining software requirements derived from system requirements and architecture decisions.",
      },
      {
        id: "swe1-q2",
        quizId: "swe1-quiz",
        type: "multiple-choice",
        text: "Which of the following is a key output of the SWE.1 process?",
        questionText: "Which of the following is a key output of the SWE.1 process?",
        options: [
          { id: "a", text: "Software architectural design specification" },
          { id: "b", text: "Software requirements specification" },
          { id: "c", text: "Unit test report" },
          { id: "d", text: "Integration test specification" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "The Software Requirements Specification (SRS) is the primary output of SWE.1.",
      },
      {
        id: "swe1-q3",
        quizId: "swe1-quiz",
        type: "multiple-choice",
        text: "Bidirectional traceability in SWE.1 means:",
        questionText: "Bidirectional traceability in SWE.1 means:",
        options: [
          { id: "a", text: "Requirements are traced only downward to design" },
          { id: "b", text: "Each software requirement can be traced to system requirements and vice versa" },
          { id: "c", text: "Test cases cover all requirements" },
          { id: "d", text: "Code is traceable to architecture only" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Bidirectional traceability ensures every software requirement maps to a system requirement and every system requirement is covered by at least one software requirement.",
      },
      {
        id: "swe1-q4",
        quizId: "swe1-quiz",
        type: "multiple-choice",
        text: "Which activity is NOT part of SWE.1?",
        questionText: "Which activity is NOT part of SWE.1?",
        options: [
          { id: "a", text: "Analyzing and documenting software requirements" },
          { id: "b", text: "Evaluating software requirements for testability" },
          { id: "c", text: "Designing the software architecture" },
          { id: "d", text: "Agreeing on software requirements with stakeholders" },
        ],
        correctAnswer: "c",
        points: 1,
        explanation:
          "Designing the software architecture is the responsibility of SWE.2, not SWE.1.",
      },
      {
        id: "swe1-q5",
        quizId: "swe1-quiz",
        type: "multiple-choice",
        text: "What does 'impact analysis' mean in the context of SWE.1?",
        questionText: "What does 'impact analysis' mean in the context of SWE.1?",
        options: [
          { id: "a", text: "Analysing the performance impact of code changes" },
          { id: "b", text: "Assessing how a requirements change affects other requirements and design" },
          { id: "c", text: "Measuring the test coverage impact" },
          { id: "d", text: "Evaluating the business impact of the product" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Impact analysis in requirements management determines the ripple effects of a proposed change across related requirements and downstream artifacts.",
      },
    ],
  },
  {
    id: "swe2-quiz",
    title: "SWE.2 – Software Architectural Design",
    description:
      "Test your knowledge of software architectural design principles and their application within ASPICE SWE.2.",
    category: "Architecture",
    difficulty: "hard",
    timeLimit: 20,
    passingScore: 70,
    isPublished: true,
    attemptCount: 1,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe2-q1",
        quizId: "swe2-quiz",
        type: "multiple-choice",
        text: "The primary goal of SWE.2 is to:",
        questionText: "The primary goal of SWE.2 is to:",
        options: [
          { id: "a", text: "Write unit tests for all software components" },
          { id: "b", text: "Develop a software architecture that fulfils all software requirements" },
          { id: "c", text: "Verify software requirements against system requirements" },
          { id: "d", text: "Integrate software components into a working system" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "SWE.2 aims to establish a software architecture that allocates all software requirements to software components.",
      },
      {
        id: "swe2-q2",
        quizId: "swe2-quiz",
        type: "multiple-choice",
        text: "Which artifact directly results from SWE.2?",
        questionText: "Which artifact directly results from SWE.2?",
        options: [
          { id: "a", text: "Software requirements specification" },
          { id: "b", text: "Software architectural design specification" },
          { id: "c", text: "Software unit test specification" },
          { id: "d", text: "System test specification" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "The Software Architectural Design Specification is the key output of SWE.2.",
      },
      {
        id: "swe2-q3",
        quizId: "swe2-quiz",
        type: "multiple-choice",
        text: "Interface definition in SWE.2 refers to:",
        questionText: "Interface definition in SWE.2 refers to:",
        options: [
          { id: "a", text: "User interface screen layouts" },
          { id: "b", text: "Specifying the communication between software components" },
          { id: "c", text: "Hardware/software interfaces only" },
          { id: "d", text: "Database schema design" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Interface definition in SWE.2 specifies the communication protocols and data formats between software components.",
      },
      {
        id: "swe2-q4",
        quizId: "swe2-quiz",
        type: "multiple-choice",
        text: "Dynamic behaviour in a software architecture refers to:",
        questionText: "Dynamic behaviour in a software architecture refers to:",
        options: [
          { id: "a", text: "Compile-time binding of components" },
          { id: "b", text: "The runtime interactions and state transitions between components" },
          { id: "c", text: "The static allocation of requirements" },
          { id: "d", text: "Memory layout at startup" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Dynamic behaviour describes how components interact at runtime, including sequences, events, and state transitions.",
      },
    ],
  },
  {
    id: "swe3-quiz",
    title: "SWE.3 – Software Detailed Design & Unit Construction",
    description:
      "Evaluate your grasp of detailed software design and unit construction activities as defined by ASPICE SWE.3.",
    category: "Design & Coding",
    difficulty: "medium",
    timeLimit: 15,
    passingScore: 70,
    isPublished: true,
    attemptCount: 0,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe3-q1",
        quizId: "swe3-quiz",
        type: "multiple-choice",
        text: "SWE.3 covers which level of software design?",
        questionText: "SWE.3 covers which level of software design?",
        options: [
          { id: "a", text: "System-level architecture" },
          { id: "b", text: "High-level component architecture" },
          { id: "c", text: "Detailed design of individual software units" },
          { id: "d", text: "Integration design between systems" },
        ],
        correctAnswer: "c",
        points: 1,
        explanation:
          "SWE.3 focuses on the detailed design of individual software units and their construction (coding).",
      },
      {
        id: "swe3-q2",
        quizId: "swe3-quiz",
        type: "multiple-choice",
        text: "Which statement best describes a 'software unit' in ASPICE SWE.3?",
        questionText: "Which statement best describes a 'software unit' in ASPICE SWE.3?",
        options: [
          { id: "a", text: "The complete deliverable software product" },
          { id: "b", text: "The smallest separately testable element of the software" },
          { id: "c", text: "A software subsystem containing multiple components" },
          { id: "d", text: "A hardware module controlled by software" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "A software unit is the smallest separately testable element – typically a function, class, or module.",
      },
      {
        id: "swe3-q3",
        quizId: "swe3-quiz",
        type: "multiple-choice",
        text: "Coding standards in SWE.3 are primarily applied to:",
        questionText: "Coding standards in SWE.3 are primarily applied to:",
        options: [
          { id: "a", text: "Ensure consistent documentation quality" },
          { id: "b", text: "Improve the safety, maintainability, and readability of source code" },
          { id: "c", text: "Reduce integration test effort" },
          { id: "d", text: "Automate the build process" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Coding standards (e.g., MISRA-C) improve safety, maintainability, and readability, reducing defect rates.",
      },
    ],
  },
  {
    id: "swe4-quiz",
    title: "SWE.4 – Software Unit Verification",
    description:
      "Check your understanding of unit verification strategies, static analysis, and test coverage as required by ASPICE SWE.4.",
    category: "Testing",
    difficulty: "medium",
    timeLimit: 15,
    passingScore: 70,
    isPublished: true,
    attemptCount: 0,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe4-q1",
        quizId: "swe4-quiz",
        type: "multiple-choice",
        text: "The main objective of SWE.4 is to:",
        questionText: "The main objective of SWE.4 is to:",
        options: [
          { id: "a", text: "Design software units based on architecture" },
          { id: "b", text: "Verify that each software unit meets its detailed design" },
          { id: "c", text: "Integrate units into subsystems" },
          { id: "d", text: "Conduct system-level qualification tests" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "SWE.4 verifies that each software unit correctly implements its detailed design through testing and static analysis.",
      },
      {
        id: "swe4-q2",
        quizId: "swe4-quiz",
        type: "multiple-choice",
        text: "Statement coverage (C0) in unit testing means:",
        questionText: "Statement coverage (C0) in unit testing means:",
        options: [
          { id: "a", text: "Every branch in the code is executed at least once" },
          { id: "b", text: "Every executable statement in the code is executed at least once" },
          { id: "c", text: "All possible paths through the code are executed" },
          { id: "d", text: "Every condition in the code evaluates to both true and false" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "C0 (statement coverage) requires every executable statement to be executed by at least one test case.",
      },
      {
        id: "swe4-q3",
        quizId: "swe4-quiz",
        type: "multiple-choice",
        text: "Static analysis in SWE.4 is used to:",
        questionText: "Static analysis in SWE.4 is used to:",
        options: [
          { id: "a", text: "Execute test cases and measure runtime performance" },
          { id: "b", text: "Detect defects in source code without executing it" },
          { id: "c", text: "Generate test data automatically" },
          { id: "d", text: "Profile memory usage at runtime" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Static analysis tools (e.g., Polyspace, PC-lint) inspect source code without execution to find defects like undefined behaviour.",
      },
    ],
  },
  {
    id: "swe5-quiz",
    title: "SWE.5 – Software Integration & Integration Test",
    description:
      "Test your knowledge of software integration strategies and integration testing practices defined in ASPICE SWE.5.",
    category: "Integration",
    difficulty: "hard",
    timeLimit: 20,
    passingScore: 70,
    isPublished: true,
    attemptCount: 2,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe5-q1",
        quizId: "swe5-quiz",
        type: "multiple-choice",
        text: "SWE.5 focuses on:",
        questionText: "SWE.5 focuses on:",
        options: [
          { id: "a", text: "Verifying individual software units in isolation" },
          { id: "b", text: "Integrating software units into a coherent software system and testing interfaces" },
          { id: "c", text: "Qualifying the complete system against customer requirements" },
          { id: "d", text: "Analysing software requirements for consistency" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "SWE.5 integrates verified software units step-by-step and tests the interactions between them.",
      },
      {
        id: "swe5-q2",
        quizId: "swe5-quiz",
        type: "multiple-choice",
        text: "Which integration strategy builds the system from the top of the hierarchy downward?",
        questionText: "Which integration strategy builds the system from the top of the hierarchy downward?",
        options: [
          { id: "a", text: "Bottom-up integration" },
          { id: "b", text: "Big-bang integration" },
          { id: "c", text: "Top-down integration" },
          { id: "d", text: "Continuous integration" },
        ],
        correctAnswer: "c",
        points: 1,
        explanation:
          "Top-down integration starts with the highest-level components and integrates lower-level components progressively using stubs.",
      },
    ],
  },
  {
    id: "swe6-quiz",
    title: "SWE.6 – Software Qualification Test",
    description:
      "Evaluate your understanding of software qualification testing and its role in demonstrating compliance with software requirements per ASPICE SWE.6.",
    category: "Testing",
    difficulty: "easy",
    timeLimit: 10,
    passingScore: 70,
    isPublished: true,
    attemptCount: 0,
    maxAttempts: 3,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    activeSession: null,
    questions: [
      {
        id: "swe6-q1",
        quizId: "swe6-quiz",
        type: "multiple-choice",
        text: "The purpose of SWE.6 is to:",
        questionText: "The purpose of SWE.6 is to:",
        options: [
          { id: "a", text: "Design and integrate software components" },
          { id: "b", text: "Verify that the integrated software meets all software requirements" },
          { id: "c", text: "Verify individual units in isolation" },
          { id: "d", text: "Perform system-level acceptance testing with the customer" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "SWE.6 performs qualification testing on the integrated software to confirm all software requirements are satisfied.",
      },
      {
        id: "swe6-q2",
        quizId: "swe6-quiz",
        type: "multiple-choice",
        text: "A regression test in SWE.6 is run to:",
        questionText: "A regression test in SWE.6 is run to:",
        options: [
          { id: "a", text: "Measure code coverage for the first time" },
          { id: "b", text: "Confirm that previously passing tests still pass after a change" },
          { id: "c", text: "Discover new requirements from stakeholders" },
          { id: "d", text: "Validate hardware components" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Regression testing ensures that changes or bug fixes have not broken existing functionality.",
      },
      {
        id: "swe6-q3",
        quizId: "swe6-quiz",
        type: "multiple-choice",
        text: "Traceability between SWE.6 test cases and software requirements serves to:",
        questionText: "Traceability between SWE.6 test cases and software requirements serves to:",
        options: [
          { id: "a", text: "Reduce the number of test cases needed" },
          { id: "b", text: "Demonstrate that every requirement is covered by at least one test" },
          { id: "c", text: "Replace the need for unit testing" },
          { id: "d", text: "Automate the test execution pipeline" },
        ],
        correctAnswer: "b",
        points: 1,
        explanation:
          "Traceability from requirements to test cases proves complete test coverage of the software requirements specification.",
      },
    ],
  },
]

export const MOCK_ATTEMPTS: QuizAttempt[] = [
  {
    id: "attempt-1",
    userId: "user-1",
    quizId: "swe2-quiz",
    answers: [
      { questionId: "swe2-q1", selectedAnswer: "b" },
      { questionId: "swe2-q2", selectedAnswer: "b" },
      { questionId: "swe2-q3", selectedAnswer: "b" },
      { questionId: "swe2-q4", selectedAnswer: "a" },
    ],
    score: 75,
    totalQuestions: 4,
    correctAnswers: 3,
    passed: true,
    startedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
    quiz: MOCK_QUIZZES.find((q) => q.id === "swe2-quiz"),
  },
  {
    id: "attempt-2",
    userId: "user-1",
    quizId: "swe5-quiz",
    answers: [
      { questionId: "swe5-q1", selectedAnswer: "b" },
      { questionId: "swe5-q2", selectedAnswer: "a" },
    ],
    score: 50,
    totalQuestions: 2,
    correctAnswers: 1,
    passed: false,
    startedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
    quiz: MOCK_QUIZZES.find((q) => q.id === "swe5-quiz"),
  },
  {
    id: "attempt-3",
    userId: "user-1",
    quizId: "swe5-quiz",
    answers: [
      { questionId: "swe5-q1", selectedAnswer: "b" },
      { questionId: "swe5-q2", selectedAnswer: "c" },
    ],
    score: 100,
    totalQuestions: 2,
    correctAnswers: 2,
    passed: true,
    startedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 12 * 60 * 60 * 1000 + 6 * 60 * 1000).toISOString(),
    quiz: MOCK_QUIZZES.find((q) => q.id === "swe5-quiz"),
  },
]

export function getQuizById(id: string): Quiz | undefined {
  return MOCK_QUIZZES.find((q) => q.id === id)
}

export function getAttemptById(id: string): QuizAttempt | undefined {
  return MOCK_ATTEMPTS.find((a) => a.id === id)
}
